exclude: migrations
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-merge-conflict
    - id: debug-statements

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: [toml]

-   repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        files: .py$
        additional_dependencies: ["click==8.0.4"]
